export * from './person/Person'
export * from './img/Img'
export * from './loader/Loader'
export * from './group/Group'
export * from './button/Button'
export * from './badge/Badge'
export * from './progress/ProgressBar'
export * from './person-list/PersonList'
export * from './work/OurWork'
export * from './stack/Stack'
export * from './header/Header';
export * from './footer/Footer';
export * from './сustom-image/СustomImage';
export * from './h2/H2';
export * from './breadcrumbs/Breadcrumbs';
